apiVersion: v1
kind: Service
metadata:
  name: "gateway-service"
  labels:
    app: soundunder
spec:
  type: LoadBalancer
  selector:
    app: soundunder
  ports:
  - port: 80
    targetPort: 80
    name: "gateway-service"
